/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'HiloToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.HiloToken__factory>
getContractFactory(name: 'RewardWrapper', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RewardWrapper__factory>

  getContractAt(name: 'HiloToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.HiloToken>
getContractAt(name: 'RewardWrapper', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RewardWrapper>

  deployContract(name: 'HiloToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HiloToken>
deployContract(name: 'RewardWrapper', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardWrapper>

  deployContract(name: 'HiloToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HiloToken>
deployContract(name: 'RewardWrapper', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardWrapper>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  